### ISSUE TITLE
try making Dart's dynamic type map to Anything

### ISSUE THREAD

**Issue by jvasileff** [jvasileff/ceylon-dart#44]
Dart dynamic is currently mapped to:

* `Nothing` for return types
* `Anything` for parameter types
* `Nothing` for type arguments (since generics in Dart are always covariant)

The idea was to be permissive, and somewhat match Java's pre-generics type safety.

But, this is probably too permissive. So let's try making dynamic always map to `Anything`, and see if the `assert`s are manageable.

See also 234ef055b411bc8819b7a33a07b181cbf73a1380

**Comment by jvasileff** [comment]
Done, for now.

**Comment by gavinking** [comment]
@jvasileff It would be totally crazy to make Dart's dynamic type map to `dynamic`, I suppose?

**Comment by jvasileff** [comment]
@gavinking I have been trying to figure out how `dynamic` might help with interop.

But for this, the problems I've had so far are for *type arguments* in cases the Dart api resorts to something like Java's raw types. For example, `Future<T>.then()`'s signature is:

```dart
Future/*<S>*/ then/*<S>*/(/*=S*/ onValue(T value), { Function onError });
```
Note the commented out type params. I suspect this is because:

1. They don't support union types! The return type really needs to be `Future<S | E>`, with `E` being the return type of the `onError()` parameter, and
2. They magically unwrap the result of `onValue` if it is a future. So if `onValue` returns `Future<String>`, `S` will actually be `String`.

Another example is this, where for whatever reason they couldn't get generics to work:

```dart
  Stream/*<S>*/ transform/*<S>*/(
      StreamTransformer<T, dynamic/*=S*/ > streamTransformer) {
    return streamTransformer.bind(this);
  }
```

Now, my understanding is that Ceylon does not support `dynamic` as a type argument, so it's not really an option here. If it *did*, then I guess we'd have to consider which would be easier to use: `assert`s or `dynamic` blocks.

**Comment by gavinking** [comment]
> But for this, the problems I've had so far are for type arguments in cases the Dart api resorts to something like Java's raw types. 

Ah, right, sure, I missed that in the issue description.

> Now, my understanding is that Ceylon does not support dynamic as a type argument

Right, so in principle there was half of a plan to change that in order to make @lucaswerkmeister's work on typescript support easier. It's interesting to see that it's also useful here.

But I guess what you're saying is that `List<dynamic>` is actually somewhat equivalent to a Java _raw type_. That is a connection I had simply *never* made before, and never even suspected. So perhaps allowing "dynamic" instantiations of generic types would help solve interop problems even in the _Java_ backend!

> So let's try making dynamic always map to `Anything`, and see if the asserts are manageable.

Actually this now seems correct to me. Given that all generic types in Dart are by nature covariant (right?) a `List<Anything>` is actually just like a `List<out Object>` in Java which is the mapping we use for a raw `List` in Java.
